name: Crear Ejecutable Windows
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Convertir HTML a EXE
        run: |
          npx nativefier "file:///${{ github.workspace }}/index.html" --name "UGR-Test" --internal-urls ".*" --single-instance
          
      - name: Guardar el archivo EXE
        uses: actions/upload-artifact@v3
        with:
          name: Juego-Psicomotricidad-EXE
          path: ./*win32-x64/
